// Lazy loaded components for the standalone admin portal.
export const adminLazyComponents = {
  AdminLogin: () => import("../views/auth/pages/AdminLogin"),
  StaffLogin: () => import("../views/auth/pages/StaffLogin"),
  AdminDashboard: () => import("../views/admin/Dashboard"),
  AdminProductsList: () => import("../views/admin/Products/List"),
  AdminProductsAdd: () => import("../views/admin/Products/Add"),
  AdminProductsCsvBuilder: () => import("../views/admin/Products/CsvBuilder"),
  AdminProductsBestSellers: () => import("../views/admin/Products/BestSellers"),
  AdminProductsNewArrivals: () => import("../views/admin/Products/NewArrivals"),
  AdminProductsPromotions: () => import("../views/admin/Products/Promotions"),
  AdminProductsSold: () => import("../views/admin/Products/Sold"),
  AdminProductsEdit: () => import("../views/admin/Products/Edit"),
  AdminAllReviews: () => import("../views/admin/Reviews/All"),
  AdminPositiveReviews: () => import("../views/admin/Reviews/Positive"),
  AdminNegativeReviews: () => import("../views/admin/Reviews/Negative"),
  AdminBanners: () => import("../views/admin/Banners"),
  AdminUsers: () => import("../views/admin/Users"),
  AdminStaff: () => import("../views/admin/Staff"),
  AdminOrdersList: () => import("../views/admin/Orders/List"),
  AdminOrderDetails: () => import("../views/admin/Orders/Details"),
  AdminReports: () => import("../views/admin/Reports"),
  AdminCashReport: () => import("../views/admin/CashReport"),
  SellerDashboard: () => import("../views/admin/SellerDashboard"),
  SellerPaymentQueue: () => import("../views/admin/PaymentQueue"),
  DeliveryDashboard: () => import("../views/admin/DeliveryDashboard"),
};

export const adminRoutes = [
  { path: "/admin", component: "AdminDashboard", allowedRoles: ["admin"] },
  { path: "/admin/products", component: "AdminProductsList", allowedRoles: ["admin"] },
  { path: "/admin/products/add", component: "AdminProductsAdd", allowedRoles: ["admin"] },
  { path: "/admin/products/csv-builder", component: "AdminProductsCsvBuilder", allowedRoles: ["admin"] },
  { path: "/admin/products/best-sellers", component: "AdminProductsBestSellers", allowedRoles: ["admin"] },
  { path: "/admin/products/new-arrivals", component: "AdminProductsNewArrivals", allowedRoles: ["admin"] },
  { path: "/admin/products/promotions", component: "AdminProductsPromotions", allowedRoles: ["admin"] },
  { path: "/admin/products/sold", component: "AdminProductsSold", allowedRoles: ["admin"] },
  { path: "/admin/products/edit/:id", component: "AdminProductsEdit", allowedRoles: ["admin"] },
  { path: "/admin/reviews", component: "AdminAllReviews", allowedRoles: ["admin"] },
  { path: "/admin/reviews/positive", component: "AdminPositiveReviews", allowedRoles: ["admin"] },
  { path: "/admin/reviews/negative", component: "AdminNegativeReviews", allowedRoles: ["admin"] },
  { path: "/admin/banners", component: "AdminBanners", allowedRoles: ["admin"] },
  { path: "/admin/users", component: "AdminUsers", allowedRoles: ["admin"] },
  { path: "/admin/orders", component: "AdminOrdersList", allowedRoles: ["admin"] },
  { path: "/admin/orders/:id", component: "AdminOrderDetails", allowedRoles: ["admin"] },
  { path: "/admin/cash-report", component: "AdminCashReport", allowedRoles: ["admin", "seller"] },
  { path: "/seller/dashboard", component: "SellerDashboard", allowedRoles: ["seller"] },
  { path: "/seller/orders", component: "AdminOrdersList", allowedRoles: ["seller"] },
  { path: "/seller/orders/:id", component: "AdminOrderDetails", allowedRoles: ["seller"] },
  { path: "/seller/payment-queue", component: "SellerPaymentQueue", allowedRoles: ["seller"] },
  { path: "/seller/cash-report", component: "AdminCashReport", allowedRoles: ["seller"] },
  { path: "/delivery/orders", component: "DeliveryDashboard", allowedRoles: ["delivery"] },
  { path: "/delivery/orders/:id", component: "AdminOrderDetails", allowedRoles: ["delivery"] },
  { path: "/admin/seller", component: "AdminStaff", allowedRoles: ["admin"] },
  { path: "/admin/staff", component: "AdminStaff", allowedRoles: ["admin"] },
  { path: "/admin/reports", component: "AdminReports", allowedRoles: ["admin"] },
];
