// Lazy loaded components for the standalone admin portal.
export const adminLazyComponents = {
  AdminLogin: () => import("../views/auth/pages/AdminLogin"),
  StaffLogin: () => import("../views/auth/pages/StaffLogin"),
  AdminDashboard: () => import("../views/admin/Dashboard"),
  AdminProductsList: () => import("../views/admin/Products/List"),
  AdminProductsAdd: () => import("../views/admin/Products/Add"),
  AdminProductsCsvBuilder: () => import("../views/admin/Products/CsvBuilder"),
  AdminProductsEdit: () => import("../views/admin/Products/Edit"),
  AdminBanners: () => import("../views/admin/Banners"),
  AdminUsers: () => import("../views/admin/Users"),
  AdminStaff: () => import("../views/admin/Staff"),
  AdminOrdersList: () => import("../views/admin/Orders/List"),
  AdminOrderDetails: () => import("../views/admin/Orders/Details"),
  AdminReports: () => import("../views/admin/Reports"),
  AdminCashReport: () => import("../views/admin/CashReport"),
  SellerDashboard: () => import("../views/admin/SellerDashboard"),
  SellerPaymentQueue: () => import("../views/admin/PaymentQueue"),
};

export const adminRoutes = [
  { path: "/admin", component: "AdminDashboard", allowedRoles: ["admin"] },
  { path: "/admin/products", component: "AdminProductsList", allowedRoles: ["admin"] },
  { path: "/admin/products/add", component: "AdminProductsAdd", allowedRoles: ["admin"] },
  { path: "/admin/products/csv-builder", component: "AdminProductsCsvBuilder", allowedRoles: ["admin"] },
  { path: "/admin/products/edit/:id", component: "AdminProductsEdit", allowedRoles: ["admin"] },
  { path: "/admin/banners", component: "AdminBanners", allowedRoles: ["admin"] },
  { path: "/admin/users", component: "AdminUsers", allowedRoles: ["admin"] },
  { path: "/admin/orders", component: "AdminOrdersList", allowedRoles: ["admin"] },
  { path: "/admin/orders/:id", component: "AdminOrderDetails", allowedRoles: ["admin"] },
  { path: "/admin/cash-report", component: "AdminCashReport", allowedRoles: ["admin", "seller"] },
  { path: "/seller/dashboard", component: "SellerDashboard", allowedRoles: ["seller"] },
  { path: "/seller/orders", component: "AdminOrdersList", allowedRoles: ["seller"] },
  { path: "/seller/orders/:id", component: "AdminOrderDetails", allowedRoles: ["seller"] },
  { path: "/seller/payment-queue", component: "SellerPaymentQueue", allowedRoles: ["seller"] },
  { path: "/seller/cash-report", component: "AdminCashReport", allowedRoles: ["seller"] },
  { path: "/delivery/orders", component: "AdminOrdersList", allowedRoles: ["delivery"] },
  { path: "/delivery/orders/:id", component: "AdminOrderDetails", allowedRoles: ["delivery"] },
  { path: "/admin/seller", component: "AdminStaff", allowedRoles: ["admin"] },
  { path: "/admin/staff", component: "AdminStaff", allowedRoles: ["admin"] },
  { path: "/admin/reports", component: "AdminReports", allowedRoles: ["admin"] },
];
