// Lazy loaded components for the standalone admin portal.
export const adminLazyComponents = {
  AdminLogin: () => import("../views/auth/pages/AdminLogin"),
  StaffLogin: () => import("../views/auth/pages/StaffLogin"),
  StaffForgotPassword: () => import("../views/auth/pages/StaffForgotPassword"),
  AdminDashboard: () => import("../views/admin/Dashboard"),
  AdminProductsList: () => import("../views/admin/Products/List"),
  AdminProductsAdd: () => import("../views/admin/Products/Add"),
  AdminProductsBestSellers: () => import("../views/admin/Products/BestSellers"),
  AdminProductsNewArrivals: () => import("../views/admin/Products/NewArrivals"),
  AdminProductsPromotions: () => import("../views/admin/Products/Promotions"),
  AdminProductsSold: () => import("../views/admin/Products/Sold"),
  AdminProductsEdit: () => import("../views/admin/Products/Edit"),
  AdminProductDetails: () => import("../views/admin/Products/Details"),
  AdminAllReviews: () => import("../views/admin/Reviews/All"),
  AdminPositiveReviews: () => import("../views/admin/Reviews/Positive"),
  AdminNegativeReviews: () => import("../views/admin/Reviews/Negative"),
  AdminBanners: () => import("../views/admin/Banners"),
  AdminUsers: () => import("../views/admin/Users"),
  AdminStaff: () => import("../views/admin/Staff"),
  AdminNotifications: () => import("../views/admin/Notifications"),
  AdminOrdersList: () => import("../views/admin/Orders/List"),
  AdminOrderDetails: () => import("../views/admin/Orders/Details"),
  AdminSupportTickets: () => import("../views/admin/SupportTickets"),
  AdminSupportTicketDetails: () => import("../views/admin/SupportTickets/Details"),
  AdminFinancialSettings: () => import("../views/admin/FinancialSettings"),
  AdminCashReport: () => import("../views/admin/CashReport"),
  AdminSuppliersList: () => import("../views/admin/Suppliers/List"),
  AdminSupplierDetails: () => import("../views/admin/Suppliers/Details"),
  AdminPurchaseOrdersList: () => import("../views/admin/PurchaseOrders/List"),
  AdminPurchaseOrderCreate: () => import("../views/admin/PurchaseOrders/Create"),
  AdminPurchaseOrderDetails: () => import("../views/admin/PurchaseOrders/Details"),
  SellerDashboard: () => import("../views/admin/SellerDashboard"),
  DeliveryDashboard: () => import("../views/admin/DeliveryDashboard"),
  StaffAccount: () => import("../views/admin/StaffAccount"),
  AdminNetRevenue: () => import("../views/admin/NetRevenue"),
};

export const adminRoutes = [
  { path: "/admin", component: "AdminDashboard", allowedRoles: ["admin"] },
  { path: "/admin/products", component: "AdminProductsList", allowedRoles: ["admin"] },
  { path: "/admin/products/add", component: "AdminProductsAdd", allowedRoles: ["admin"] },
  { path: "/admin/products/best-sellers", component: "AdminProductsBestSellers", allowedRoles: ["admin"] },
  { path: "/admin/products/new-arrivals", component: "AdminProductsNewArrivals", allowedRoles: ["admin"] },
  { path: "/admin/products/promotions", component: "AdminProductsPromotions", allowedRoles: ["admin"] },
  { path: "/admin/products/sold", component: "AdminProductsSold", allowedRoles: ["admin"] },
  { path: "/admin/products/edit/:id", component: "AdminProductsEdit", allowedRoles: ["admin"] },
  { path: "/admin/products/:id", component: "AdminProductDetails", allowedRoles: ["admin"] },
  { path: "/admin/reviews", component: "AdminAllReviews", allowedRoles: ["admin"] },
  { path: "/admin/reviews/positive", component: "AdminPositiveReviews", allowedRoles: ["admin"] },
  { path: "/admin/reviews/negative", component: "AdminNegativeReviews", allowedRoles: ["admin"] },
  { path: "/admin/banners", component: "AdminBanners", allowedRoles: ["admin"] },
  { path: "/admin/users", component: "AdminUsers", allowedRoles: ["admin"] },
  { path: "/admin/notifications", component: "AdminNotifications", allowedRoles: ["admin"] },
  { path: "/admin/orders", component: "AdminOrdersList", allowedRoles: ["admin"] },
  { path: "/admin/orders/:id", component: "AdminOrderDetails", allowedRoles: ["admin"] },
  { path: "/admin/support/tickets", component: "AdminSupportTickets", allowedRoles: ["admin"] },
  { path: "/admin/support/tickets/:ticketNumber", component: "AdminSupportTicketDetails", allowedRoles: ["admin"] },
  { path: "/admin/cash-report", component: "AdminCashReport", allowedRoles: ["admin", "seller"] },
  { path: "/admin/suppliers", component: "AdminSuppliersList", allowedRoles: ["admin"] },
  { path: "/admin/suppliers/:id", component: "AdminSupplierDetails", allowedRoles: ["admin"] },
  { path: "/admin/purchase-orders", component: "AdminPurchaseOrdersList", allowedRoles: ["admin"] },
  { path: "/admin/purchase-orders/new", component: "AdminPurchaseOrderCreate", allowedRoles: ["admin"] },
  { path: "/admin/purchase-orders/:id", component: "AdminPurchaseOrderDetails", allowedRoles: ["admin"] },
  { path: "/seller/dashboard", component: "SellerDashboard", allowedRoles: ["seller"] },
  { path: "/seller/notifications", component: "AdminNotifications", allowedRoles: ["seller"] },
  { path: "/seller/orders", component: "AdminOrdersList", allowedRoles: ["seller"] },
  { path: "/seller/orders/:id", component: "AdminOrderDetails", allowedRoles: ["seller"] },
  { path: "/seller/cash-report", component: "AdminCashReport", allowedRoles: ["seller"] },
  { path: "/seller/account", component: "StaffAccount", allowedRoles: ["seller"] },
  { path: "/delivery/orders", component: "DeliveryDashboard", allowedRoles: ["delivery"] },
  { path: "/delivery/orders/:id", component: "AdminOrderDetails", allowedRoles: ["delivery"] },
  { path: "/delivery/account", component: "StaffAccount", allowedRoles: ["delivery"] },
  { path: "/admin/seller", component: "AdminStaff", allowedRoles: ["admin"] },
  { path: "/admin/staff", component: "AdminStaff", allowedRoles: ["admin"] },
  { path: "/admin/financial-settings", component: "AdminFinancialSettings", allowedRoles: ["admin"] },
  { path: "/admin/net-revenue", component: "AdminNetRevenue", allowedRoles: ["admin"] },
];
